# Generated by Django 2.1.3 on 2018-11-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Clock-event time'),
        ),
    ]
