# Generated by Django 2.1.3 on 2018-11-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181106_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='type',
            field=models.CharField(choices=[('IN', 'Clock-In'), ('OUT', 'Clock-Out')], max_length=3),
        ),
    ]
